
platform :ios, '7.0'

target 'music' do
    pod 'Reachability'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'BlocksKit'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    pod 'KVOController'
    pod 'SDWebImage'
    pod 'Mantle'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'WebViewJavascriptBridge'
    pod 'JPush'
    pod 'AVOSCloud'
    pod 'AVOSCloudIM'
end
